name: CI for stripe-samples/accept-a-payment
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'

env:
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  server_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - server_type: ruby
            server_image: ruby:3.0
          - server_type: ruby
            server_image: ruby:2.6
          - server_type: node
            server_image: node:14.17
          - server_type: node
            server_image: node:12.22
          - server_type: python
            server_image: python:3.9
          - server_type: python
            server_image: python:3.6
          - server_type: java
            server_image: maven:3.8-openjdk-16
          - server_type: java
            server_image: maven:3.8-openjdk-8
          - server_type: go
            server_image: golang:1.16
          - server_type: go
            server_image: golang:1.15
        target:
          - sample: custom-payment-flow
            tests: custom_payment_flow_server_spec.rb
          - sample: prebuilt-checkout-page
            tests: prebuilt_checkout_page_spec.rb
        include:
          - runtime:
              server_type: node-typescript
              server_image: node:14.17
            target:
              sample: custom-payment-flow
              tests: custom_payment_flow_server_spec.rb
          - runtime:
              server_type: node-typescript
              server_image: node:12.22
            target:
              sample: custom-payment-flow
              tests: custom_payment_flow_server_spec.rb
          - runtime:
              server_type: dotnet
              server_image: mcr.microsoft.com/dotnet/sdk:6.0
            target:
              sample: custom-payment-flow
              tests: custom_payment_flow_server_spec.rb
          - runtime:
              server_type: dotnet
              server_image: mcr.microsoft.com/dotnet/sdk:5.0
            target:
              sample: prebuilt-checkout-page
              tests: prebuilt_checkout_page_spec.rb
          - runtime:
              server_type: dotnet
              server_image: mcr.microsoft.com/dotnet/sdk:3.1
            target:
              sample: prebuilt-checkout-page
              tests: prebuilt_checkout_page_spec.rb
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'

      - name: Setup dependencies
        run: |
          source sample-ci/helpers.sh
          setup_dependencies

      - name: Run tests
        run: |
          source sample-ci/helpers.sh

          install_docker_compose_settings
          export STRIPE_WEBHOOK_SECRET=$(retrieve_webhook_secret)
          cat <<EOF >> .env
            DOMAIN=http://web:4242
            PRICE=${{ secrets.TEST_PRICE }}
            PAYMENT_METHOD_TYPES="card"
          EOF

          configure_docker_compose_for_integration "${{ matrix.target.sample }}" "${{ matrix.runtime.server_type }}" ../../client/html "${{ matrix.runtime.server_image }}"

          docker-compose up -d && wait_web_server
          docker-compose exec -T runner bundle exec rspec spec/${{ matrix.target.tests }}

      - name: Collect debug information
        if: ${{ failure() }}
        run: |
          cat .env
          cat docker-compose.yml
          docker-compose ps -a
          docker-compose logs web

  e2e_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        implementation:
          - client_type: html
            server_url: http://web:4242
            profile: e2e
          - client_type: react-cra
            server_url: http://frontend:3000
            profile: frontend
        target:
          - sample: custom-payment-flow
            tests: custom_payment_flow_e2e_spec.rb
          - sample: prebuilt-checkout-page
            tests: prebuilt_checkout_page_e2e_spec.rb
          - sample: payment-element
            tests: payment_element_e2e_spec.rb
    env:
      SERVER_URL: ${{ matrix.implementation.server_url }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'

      - name: Setup dependencies
        run: |
          source sample-ci/helpers.sh
          setup_dependencies

      - name: Prepare tests
        run: |
          echo "$(cat ${{ matrix.target.sample }}/client/react-cra/package.json | jq '.proxy = "http://web:4242"')" > ${{ matrix.target.sample }}/client/react-cra/package.json

      - name: Run tests
        run: |
          source sample-ci/helpers.sh

          install_docker_compose_settings
          export STRIPE_WEBHOOK_SECRET=$(retrieve_webhook_secret)
          cat <<EOF >> .env
          DOMAIN=${{ matrix.implementation.server_url }}
          PRICE=${{ secrets.TEST_PRICE }}
          PAYMENT_METHOD_TYPES="card"
          EOF

          configure_docker_compose_for_integration "${{ matrix.target.sample }}" node ../../client/${{ matrix.implementation.client_type }} node:14.17
          docker-compose --profile="${{ matrix.implementation.profile }}" up -d && wait_web_server
          command="docker-compose exec -T runner bundle exec rspec spec/${{ matrix.target.tests }}"
          $command \
            || $command --only-failures \
            || $command --only-failures --format RSpec::Github::Formatter --format progress

      - name: Collect debug information
        if: ${{ failure() }}
        run: |
          cat .env
          cat docker-compose.yml
          docker-compose ps -a
          docker-compose --profile="${{ matrix.implementation.profile }}" logs web

          docker cp $(docker-compose ps -qa runner | head -1):/work/tmp .

      - name: Upload capybara screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            tmp/capybara

  e2e_android:
    runs-on: macos-11
    env:
      STRIPE_API_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}
      PRICE: ${{ secrets.TEST_PRICE }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dependencies
        run: |
          curl -o- -L https://github.com/stripe/stripe-cli/releases/download/v1.7.0/stripe_1.7.0_mac-os_x86_64.tar.gz | sudo tar fxz - -C /usr/local/bin

      - name: Run tests (1st attempt)
        timeout-minutes: 10
        continue-on-error: true
        id: attempt1
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: .github/workflows/android_e2e.sh

      - name: Run tests (2nd attempt)
        timeout-minutes: 10
        id: attempt2
        if: steps.attempt1.outcome=='failure'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: .github/workflows/android_e2e.sh

  ios_build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd custom-payment-flow/client/ios-swiftui
          pod install
          xcodebuild build \
                     -scheme AcceptAPayment \
                     -workspace AcceptAPayment.xcworkspace/ \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED="NO" \
                     CODE_SIGN_ENTITLEMENTS="" \
                     CODE_SIGNING_ALLOWED="NO"

  e2e_react_native_android:
    runs-on: macos-11
    env:
      STRIPE_API_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}
      PRICE: ${{ secrets.TEST_PRICE }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dependencies
        run: |
          curl -o- -L https://github.com/stripe/stripe-cli/releases/download/v1.7.0/stripe_1.7.0_mac-os_x86_64.tar.gz | sudo tar fxz - -C /usr/local/bin

      - name: Run tests (1st attempt)
        timeout-minutes: 15
        continue-on-error: true
        id: attempt1
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: .github/workflows/react_native_android_e2e.sh

      - name: Run tests (2nd attempt)
        timeout-minutes: 15
        id: attempt2
        if: steps.attempt1.outcome=='failure'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: .github/workflows/react_native_android_e2e.sh

      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: react-native-android-screenshots
          path: |
            custom-payment-flow/client/react-native-expo/tmp/screenshots
